### ISSUE TITLE
Convert bot to slash commands

### ISSUE THREAD

**Issue by Chronocast** [PixEye/juke-swgoh-bot#18]
Discord now mandates using slash commands. As of Sept 1st the bot does not work in servers anymore. Any plans to update the bot to support them?

**Comment by PixEye** [comment]
Slash commands are not mandatory.
Commands still work fine if you tag the bot instead of using the "j." prefix. Examples:
```
@JsB status
@JsB GL
@JsB check prof
@JsB ps @otherPlayer
...
```

It also still works fine in DM without any prefix (as before). Examples :
```
status
GL
check prof
ps @otherPlayer
...
```

**Comment by Chronocast** [comment]
Thanks, didn't realize it worked that way.

Is there a preferred method to reach out for troubleshooting like a Discord channel or something?

**Comment by PixEye** [comment]
You can use the "author" command to get my Discord tag and DM me.
I also think about opening a dedicated Discord server. I believe that most people of the french community knows me through a bot feature for the french Mercato Discord.
